"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface AISummaryProps {
  summary: string;
}

function SparkleIcon() {
  return (
    <svg
      width="16"
      height="16"
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M8 1L9.5 6.5L15 8L9.5 9.5L8 15L6.5 9.5L1 8L6.5 6.5L8 1Z"
        fill="currentColor"
      />
    </svg>
  );
}

export default function AISummary({ summary }: AISummaryProps) {
  const [revealed, setRevealed] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleReveal = () => {
    if (revealed) return;
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      setRevealed(true);
    }, 1200);
  };

  return (
    <div className="mb-10 md:mb-14 rounded-xl border border-lavender bg-[#faf9ff] p-6">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-[#7c5cbf]">
          <SparkleIcon />
        </span>
        <p className="font-sans text-[12px] uppercase tracking-widest text-[#7c5cbf] font-medium">
          AI Summary
        </p>
      </div>

      <AnimatePresence mode="wait">
        {!revealed && !loading && (
          <motion.div
            key="prompt"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
          >
            <p className="font-sans text-[15px] text-body leading-[1.6] mb-4">
              Get a quick overview of this project generated by AI.
            </p>
            <button
              onClick={handleReveal}
              className="inline-flex items-center gap-2 font-sans text-[13px] font-medium text-[#7c5cbf] border border-lavender rounded-lg px-4 py-2 hover:bg-lavender/20 transition-colors duration-200"
            >
              <SparkleIcon />
              Generate summary
            </button>
          </motion.div>
        )}

        {loading && (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="space-y-2"
          >
            {[80, 95, 70, 85, 60].map((w, i) => (
              <div
                key={i}
                className="h-3 rounded-full bg-lavender/40 animate-pulse"
                style={{ width: `${w}%` }}
              />
            ))}
          </motion.div>
        )}

        {revealed && (
          <motion.p
            key="summary"
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, ease: "easeOut" }}
            className="font-sans text-[15px] text-body leading-[1.7]"
          >
            {summary}
          </motion.p>
        )}
      </AnimatePresence>
    </div>
  );
}
