"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface AISummaryProps {
  summary: string;
}

function SparkleIcon({ size = 16 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M8 1L9.5 6.5L15 8L9.5 9.5L8 15L6.5 9.5L1 8L6.5 6.5L8 1Z"
        fill="currentColor"
      />
    </svg>
  );
}

export default function AISummary({ summary }: AISummaryProps) {
  const [revealed, setRevealed] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleReveal = () => {
    if (revealed) return;
    setLoading(true);
    setTimeout(() => {
      setLoading(false);
      setRevealed(true);
    }, 1200);
  };

  // Split into sentences for staggered reveal
  const sentences = summary.match(/[^.!?]+[.!?]+/g) ?? [summary];

  return (
    <div className="mb-10 md:mb-14 rounded-xl border border-lavender bg-[#faf9ff] p-6">
      <div className="flex items-center gap-2 mb-3">
        <span className="text-[#7c5cbf]">
          <SparkleIcon />
        </span>
        <p className="font-sans text-[12px] uppercase tracking-widest text-[#7c5cbf] font-medium">
          AI Summary
        </p>
      </div>

      <AnimatePresence mode="wait">
        {!revealed && !loading && (
          <motion.div
            key="prompt"
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.2 }}
          >
            <p className="font-sans text-[15px] text-body leading-[1.6] mb-4">
              Get a quick overview of this project generated by AI.
            </p>
            <motion.button
              onClick={handleReveal}
              className="inline-flex items-center gap-2 font-sans text-[13px] font-medium text-[#7c5cbf] border border-lavender rounded-lg px-4 py-2"
              whileHover={{ scale: 1.03, backgroundColor: "rgba(206, 198, 255, 0.2)" }}
              whileTap={{ scale: 0.97 }}
              transition={{ type: "spring", stiffness: 400, damping: 22 }}
            >
              <motion.span
                animate={{ rotate: [0, 15, -15, 0] }}
                transition={{ duration: 1.8, repeat: Infinity, repeatDelay: 2 }}
              >
                <SparkleIcon />
              </motion.span>
              Generate summary
            </motion.button>
          </motion.div>
        )}

        {loading && (
          <motion.div
            key="loading"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="space-y-2.5"
          >
            {[80, 95, 70, 85, 60].map((w, i) => (
              <motion.div
                key={i}
                className="h-3 rounded-full bg-lavender/40"
                initial={{ opacity: 0, scaleX: 0.5, originX: 0 }}
                animate={{ opacity: 1, scaleX: 1 }}
                transition={{ delay: i * 0.08, duration: 0.3 }}
                style={{
                  width: `${w}%`,
                  animation: `pulse 1.5s ease-in-out ${i * 0.15}s infinite`,
                }}
              />
            ))}
          </motion.div>
        )}

        {revealed && (
          <motion.div
            key="summary"
            initial="hidden"
            animate="visible"
            variants={{
              hidden: {},
              visible: { transition: { staggerChildren: 0.08, delayChildren: 0.05 } },
            }}
          >
            {sentences.map((sentence, i) => (
              <motion.span
                key={i}
                className="font-sans text-[15px] text-body leading-[1.7]"
                variants={{
                  hidden: { opacity: 0, y: 6 },
                  visible: {
                    opacity: 1,
                    y: 0,
                    transition: { duration: 0.4, ease: [0.25, 0.1, 0.25, 1] },
                  },
                }}
              >
                {sentence.trim()}{" "}
              </motion.span>
            ))}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
